FROM ubuntu
LABEL maintainer 'Myself <myself at destroyerOfAss.com.br>'

#aqui é a variavel que por default vai ser files
ARG S3_BUCKET=files 

#aqui é o parâmetro que vai ser enviado 
ENV S3_BUCKET=${S3_BUCKET}